### ISSUE TITLE
Fail to capture when specify link node as root

### ISSUE THREAD

**Issue by azu** [bubkoo/html-to-image#174]
html-to-image fail to capture following node.

```html
<a id="test" href="https://example.com">LINK TEXT</a>
```

capture code:

```js
var node = document.getElementById('test');

htmlToImage.toPng(node)
  .then(function (dataUrl) {
    var img = new Image();
    img.src = dataUrl;
    document.body.appendChild(img);
  })
  .catch(function (error) {
    console.error('oops, something went wrong!', error);
  });
```

I've created failed test case:

- https://github.com/bubkoo/html-to-image/compare/master...azu:fail-test-capture-inline-link?expand=1

📝 Current test implement always wrap target node with `div`, It will avoid this bug.

### Expected Behavior

Capture Link node

### Current Behavior

Fail to capture and throw a next error.

```
	Failed: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
	TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
	    at px (src/util.js:5:3256)
	    at Object.getNodeWidth (src/util.js:5:3474)
	    at getImageSize (src/index.js:2:7131)
	    at src/index.js:2:7793
	    at step (src/index.js:2:5711)
	    at Object.next (src/index.js:2:2579)
	    at src/index.js:2:1679
	    at <Jasmine>
	    at __awaiter (src/index.js:2:848)
	    at toSvg (src/index.js:2:7593)
```

### Possible Solution

I do not know correct solution.

I found a workaround to use `node.getBoundingClientRect`.
When set `width` and `height`, we can avoid this error.

```js
  const rect = element.getBoundingClientRect();
  return htmlToImage.toJpeg(element, {
    width: rect.width,
    height: rect.height,
  });
```

### Steps To Reproduce

See reproduce test case

- https://github.com/bubkoo/html-to-image/compare/master...azu:fail-test-capture-inline-link?expand=1

### Your Environment

- html-to-image: v1.7.0
- OS:  macOS 11.5.1
- Browser: Chrome: 92.0.4515.131

**Comment by azu** [comment]
This issue is not resolved.
